server:
  port: 8081

spring:
  application:
    name: auth-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: 9W5XgXodMr4OQ5QGm4ReV9FbtVqnM3MCHazU14ols/k=