server:
  port: 9000

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/auth/**
            - id: news-service
              uri: lb://news-service
              predicates:
                - Path=/api/v1/news/**
            - id: teams-service
              uri: lb://teams-service
              predicates:
                - Path=/api/v1/teams/**
            - id: league-service
              uri: lb://league-service
              predicates:
                - Path=/api/v1/league/**
            - id: fixture-service
              uri: lb://fixture-service
              predicates:
                - Path=/api/v1/fixture/**
            - id: standing-service
              uri: lb://standing-service
              predicates:
                - Path=/api/v1/standing/**
          discovery:
            locator:
              enabled: true
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "http://localhost:3000"
                allowedMethods: "*"
                allowedHeaders: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

jwt:
  key: 9W5XgXodMr4OQ5QGm4ReV9FbtVqnM3MCHazU14ols/k=
