server:
  port: 8086

spring:
  application:
    name: standing-service

  datasource:
    url: jdbc:postgresql://postgres:5432/newsNewsDB
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

jwt:
  secret: 9W5XgXodMr4OQ5QGm4ReV9FbtVqnM3MCHazU14ols/k=
  access-token-expiration: 900000 # 1000 * 60 * 15 - 15 Dakika
  refresh-token-expiration: 604800000 # 1000 * 60 * 60 * 24 * 7 - 1 Hafta
